[
  [
    "CypressError: Timed out retrying after 35000ms: `cy.wait()` timed out waiting `35000ms` for the 1st request to the route: `getProgress`. No request ever occurred.






https://on.cypress.io/wait\n    at cypressErr (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:164472:18)\n    at Object.errByPath (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:164527:10)\n    at checkForXhr (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:151391:92)\n    at <unknown> (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:151414:28)\n    at tryCatcher (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:18744:23)\n    at Promise.attempt.Promise.try (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:16018:29)\n    at whenStable (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:156356:65)\n    at <unknown> (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:155797:14)\n    at tryCatcher (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:18744:23)\n    at Promise._settlePromiseFromHandler (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:16679:31)\n    at Promise._settlePromise (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:16736:18)\n    at Promise._settlePromise0 (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:16781:10)\n    at Promise._settlePromises (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:16861:18)\n    at Promise._fulfill (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:16805:18)\n    at <unknown> (https://ace-web-stg-pr-1579-3a97d57089a4.herokuapp.com/__cypress/runner/cypress_runner.js:18419:46)\nFrom Your Spec Code:\n    at Context.eval (webpack:///./support/commands.js:733:6)",
    "support/commands.js",
    "The exam can be passed and then come back to the dashboard",
    "When FLKE can be taken",
    "2023-08-22T21:54:01.223Z",
    1,
    "qa/BB/AUT-1869-Log-Cypress-errors-in-a-spreadsheet",
    "dev-web",
    "https://cloud.cypress.io/projects/2bcho5/runs/14479"
  ],
  [
    "AssertionError: Timed out retrying after 35000ms: Expected to find element: `[data-test=currentIcon]`, but never found it.\n    at Context.eval (webpack:///./integration/flvs/major/assessment/04.florida-knowledge-exam.js:119:37)",
    "integration/flvs/major/assessment/04.florida-knowledge-exam.js",
    "The exam shows as passed and can't be taken again",
    "When FLKE can be taken",
    "2023-08-22T21:56:11.127Z",
    1,
    "qa/BB/AUT-1869-Log-Cypress-errors-in-a-spreadsheet",
    "dev-web",
    "https://cloud.cypress.io/projects/2bcho5/runs/14479"
  ],
  [
    "AssertionError: Timed out retrying after 35000ms: Expected to find element: `[data-test=levelCardTitle]`, but never found it.\n    at Context.eval (webpack:///./integration/flvs/major/assessment/04.florida-knowledge-exam.js:115:33)",
    "integration/flvs/major/assessment/04.florida-knowledge-exam.js",
    "The exam can be passed and then come back to the dashboard",
    "When FLKE can be taken",
    "2023-08-22T22:00:11.399Z",
    2,
    "qa/BB/AUT-1869-Log-Cypress-errors-in-a-spreadsheet",
    "dev-web",
    "https://cloud.cypress.io/projects/2bcho5/runs/14479"
  ],
  [
    "AssertionError: Timed out retrying after 35000ms: Expected to find element: `[data-test=currentIcon]`, but never found it.\n    at Context.eval (webpack:///./integration/flvs/major/assessment/04.florida-knowledge-exam.js:119:37)",
    "integration/flvs/major/assessment/04.florida-knowledge-exam.js",
    "The exam shows as passed and can't be taken again",
    "When FLKE can be taken",
    "2023-08-22T22:02:23.132Z",
    2,
    "qa/BB/AUT-1869-Log-Cypress-errors-in-a-spreadsheet",
    "dev-web",
    "https://cloud.cypress.io/projects/2bcho5/runs/14479"
  ]
]
